import React, { useState, useEffect } from 'react';
import GlassCard from './components/GlassCard';
import GradientButton from './components/GradientButton';
import GlowOrb from './components/GlowOrb';
import SlideEditor from './components/SlideEditor';

function App() {
  const [formData, setFormData] = useState({
    title: '',
    idea: '',
    audience: '',
    tone: '',
    goal: '',
    slideCount: 10
  });
  const [isLoading, setIsLoading] = useState(false);
  const [generatedDeck, setGeneratedDeck] = useState(null);
  const [showSlideEditor, setShowSlideEditor] = useState(false);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'slideCount' ? parseInt(value, 10) : value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    
    try {
      console.log('Sending request to /api/generate/generateDeck with data:', formData);
      
      const response = await fetch('/api/generate/generateDeck', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
      
      console.log('Response status:', response.status);
      console.log('Response headers:', Object.fromEntries(response.headers.entries()));
      
      if (response.ok) {
        const result = await response.json();
        console.log('Generated deck:', result);
        
        // Set the deck data
        setGeneratedDeck(result);
        
        // Smooth scroll to the deck preview after a brief delay
        setTimeout(() => {
          const deckElement = document.querySelector('[data-deck-preview]');
          if (deckElement) {
            deckElement.scrollIntoView({ 
              behavior: 'smooth', 
              block: 'start' 
            });
          }
        }, 500);
      } else {
        const errorText = await response.text();
        console.error('Server error response:', errorText);
        
        let errorData;
        try {
          errorData = JSON.parse(errorText);
        } catch {
          errorData = { message: errorText };
        }
        
        // Handle specific error types
        if (response.status === 429) {
          throw new Error(`🚫 Rate Limit Exceeded\n\n${errorData.message || 'Too many requests. Please wait 5 minutes and try again.'}\n\nTip: Gemini API has usage limits to prevent abuse.`);
        } else if (response.status === 403) {
          throw new Error(`📊 API Quota Exceeded\n\n${errorData.message || 'Daily quota exhausted. Try again tomorrow.'}\n\nSolution: Check your Gemini API dashboard for usage limits.`);
        } else if (response.status === 401) {
          throw new Error(`🔑 API Key Error\n\n${errorData.message || 'Invalid API key.'}\n\nCheck: .env file GEMINI_API_KEY configuration.`);
        } else {
          throw new Error(`❌ Server Error (${response.status})\n\n${errorData.message || errorText}`);
        }
      }
    } catch (error) {
      console.error('Detailed error:', error);
      if (error.message.includes('Failed to fetch')) {
        console.error('❌ Connection Error: Cannot connect to the backend server. Please ensure backend server is running on port 3000 and no firewall is blocking the connection.');
      } else if (error.message.includes('Rate Limit') || error.message.includes('Quota')) {
        const useDemo = confirm(`${error.message}\n\nWould you like to see a demo deck instead?`);
        if (useDemo) {
          // Create a demo deck
          const demoDeck = {
            success: true,
            message: "Demo pitch deck loaded",
            deckId: "demo-deck",
            deck: {
              metadata: {
                deckTitle: "Demo Pitch Deck - " + formData.idea,
                createdAt: new Date().toISOString(),
                totalSlides: 3
              },
              slides: [
                {
                  title: "Demo Slide 1: Your Business Idea",
                  content: [
                    `Business: ${formData.idea}`,
                    `Target Audience: ${formData.audience}`,
                    `This is a demo deck showing the structure.`,
                    `Your actual deck would be generated by Gemini AI.`
                  ]
                },
                {
                  title: "Demo Slide 2: The Problem",
                  content: [
                    "This slide would identify market problems",
                    "Generated content would be specific to your idea",
                    "AI creates professional business language",
                    "Each slide has detailed speaker notes"
                  ]
                },
                {
                  title: "Demo Slide 3: Our Solution",
                  content: [
                    "Solution details would appear here",
                    "Competitive advantages highlighted", 
                    "Market opportunity explained",
                    "Call to action for investors"
                  ]
                }
              ]
            }
          };
          setGeneratedDeck(demoDeck);
          console.log('📋 Demo deck loaded! This shows the structure - actual decks are generated with AI.');
        }
      } else {
        console.error(`❌ Error: ${error.message}`);
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="app-container">
      {/* Fixed Navigation Header */}
      <nav className="navbar">
        <div className="nav-content">
          <div className="nav-brand">
            <span className="brand-text">Pitch Deck Agent</span>
            <div className="brand-underline"></div>
          </div>
        </div>
      </nav>

      {/* Background Glow Orbs */}
      <GlowOrb 
        size="large" 
        color="cyan" 
        style={{top: '10%', left: '5%'}} 
        animate={true}
      />
      <GlowOrb 
        size="medium" 
        color="violet" 
        style={{bottom: '20%', right: '10%'}} 
        animate={true}
      />

      {/* Main Content */}
      <main className={`main-content ${generatedDeck ? 'has-deck' : ''}`}>
        <div className="container container-sm">
          {/* Hero Section - always visible when no deck generated */}
          {!generatedDeck && (
            <GlassCard className="hero-card hero-landing" glow={true}>
              <div className="hero-icon"></div>
              <h1 className="hero-title">
                Solve your problem with precision.
              </h1>
              <p className="hero-subtitle">
                The ultimate AI companion to enhance your creativity and accelerate your project delivery.
              </p>
              <div className="hero-cta">
                <GradientButton 
                  size="large" 
                  glow={true}
                  onClick={() => {
                    const formElement = document.querySelector('.form-card');
                    if (formElement) {
                      formElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
                    }
                  }}
                >
                  Get started <span className="button-accent">→</span>
                </GradientButton>
              </div>
            </GlassCard>
          )}

          {/* Form Section - always visible when no deck generated */}
          {!generatedDeck && (
            <div className="form-section">
              <div className="form-header">
                <h2 className="form-title">Create Your Pitch Deck</h2>
                <p className="form-subtitle">
                  Transform your ideas into compelling presentations with AI-powered generation
                </p>
              </div>

              <GlassCard className="form-card form-reveal" hover={true}>

            <form onSubmit={handleSubmit} className="deck-form">
              <div className="form-group">
                <label htmlFor="title" className="form-label">
                  Presentation Title *
                </label>
                <input
                  id="title"
                  name="title"
                  type="text"
                  value={formData.title}
                  onChange={handleInputChange}
                  placeholder="Revolutionizing Cat Care"
                  required
                  disabled={isLoading}
                  className={`form-input ${isLoading ? 'loading' : ''}`}
                />
              </div>

              <div className="form-group">
                <label htmlFor="idea" className="form-label">
                  Project Description *
                </label>
                <textarea
                  id="idea"
                  name="idea"
                  value={formData.idea}
                  onChange={handleInputChange}
                  placeholder="Describe your idea, audience, and what makes it different."
                  rows="4"
                  required
                  disabled={isLoading}
                  className={`form-input form-textarea ${isLoading ? 'loading' : ''}`}
                />
              </div>

              <div className="form-group">
                <label htmlFor="audience" className="form-label">
                  Target Audience *
                </label>
                <input
                  id="audience"
                  type="text"
                  name="audience"
                  value={formData.audience}
                  onChange={handleInputChange}
                  placeholder="Investors, clients, or internal team"
                  required
                  disabled={isLoading}
                  className={`form-input ${isLoading ? 'loading' : ''}`}
                />
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="tone" className="form-label">
                    Presentation Tone *
                  </label>
                  <select
                    id="tone"
                    name="tone"
                    value={formData.tone}
                    onChange={handleInputChange}
                    required
                    disabled={isLoading}
                    className={`form-input form-select ${isLoading ? 'loading' : ''}`}
                  >
                    <option value="">Select tone...</option>
                    <option value="professional">Professional & Corporate</option>
                    <option value="casual">Casual & Friendly</option>
                    <option value="technical">Technical & Data-Driven</option>
                    <option value="creative">Creative & Innovative</option>
                    <option value="confident">Confident & Bold</option>
                    <option value="conversational">Conversational & Engaging</option>
                    <option value="authoritative">Authoritative & Expert</option>
                    <option value="inspiring">Inspiring & Motivational</option>
                  </select>
                </div>

                <div className="form-group">
                  <label htmlFor="goal" className="form-label">
                    Primary Goal *
                  </label>
                  <select
                    id="goal"
                    name="goal"
                    value={formData.goal}
                    onChange={handleInputChange}
                    required
                    disabled={isLoading}
                    className={`form-input form-select ${isLoading ? 'loading' : ''}`}
                  >
                    <option value="">Select goal...</option>
                    <option value="funding">Raise Funding (Investors)</option>
                    <option value="sales">Sales Presentation</option>
                    <option value="partnership">Business Partnership</option>
                    <option value="marketing">Marketing Campaign</option>
                    <option value="product_launch">Product Launch</option>
                    <option value="team_internal">Internal Team Presentation</option>
                    <option value="client_proposal">Client Proposal</option>
                    <option value="conference">Conference/Speaking Event</option>
                  </select>
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="slideCount" className="form-label">
                  Number of Slides
                </label>
                <div className="slider-group">
                  <input
                    id="slideCount"
                    type="range"
                    name="slideCount"
                    min="5"
                    max="25"
                    step="1"
                    value={formData.slideCount}
                    onChange={handleInputChange}
                    disabled={isLoading}
                    className="form-slider"
                  />
                  <div className="slider-value">
                    {formData.slideCount}
                  </div>
                </div>
                <p className="form-help">
                  Choose between 5-25 slides for your presentation
                </p>
              </div>

              {/* Privacy Notice */}
              <div className="privacy-notice">
                <span className="privacy-icon">🔒</span>
                <span className="privacy-text">Your data stays on your device. No cloud storage.</span>
              </div>

              <GradientButton
                type="submit"
                disabled={isLoading}
                loading={isLoading}
                size="large"
                glow={true}
              >
                {isLoading ? 'Building your deck...' : (
                  <>
                    Generate Pitch Deck
                    <span className="button-accent">→</span>
                  </>
                )}
              </GradientButton>

              {/* Save Template Button */}
              <GradientButton
                type="button"
                variant="secondary"
                disabled={isLoading}
                onClick={() => {
                  const template = {
                    title: formData.title,
                    idea: formData.idea,
                    audience: formData.audience,
                    tone: formData.tone,
                    goal: formData.goal,
                    slideCount: formData.slideCount,
                    savedAt: new Date().toISOString()
                  };
                  
                  // Save to localStorage
                  const savedTemplates = JSON.parse(localStorage.getItem('pitchDeckTemplates') || '[]');
                  savedTemplates.push(template);
                  localStorage.setItem('pitchDeckTemplates', JSON.stringify(savedTemplates));
                  
                  // Show confirmation
                  alert('Template saved successfully! You can load it later from your browser storage.');
                }}
              >
                <span>💾</span>
                <span>Save Template</span>
              </GradientButton>
            </form>
          </GlassCard>
            </div>
          )}

          {/* Deck Preview Section */}
          {generatedDeck && (
            <section className="deck-preview-section" data-deck-preview>
              <div className="container">
            <GlassCard className="result-card" glow={true}>
              <div className="result-header">
                <button
                  onClick={() => setGeneratedDeck(null)}
                  className="close-button"
                  aria-label="Close preview"
                >
                  ×
                </button>
                <div className="success-icon">✅</div>
                <h2 className="result-title">
                  Your Pitch Deck is Ready!
                </h2>
              </div>

              {/* Export Actions */}
              <div className="export-section">
                <h3 className="export-title">Export Your Deck</h3>
                
                {/* Main Export Actions */}
                <div className="export-actions-main">
                  <button
                    onClick={async () => {
                      try {
                        const response = await fetch('/api/export/pdf', {
                          method: 'POST',
                          headers: { 'Content-Type': 'application/json' },
                          body: JSON.stringify({ deckId: generatedDeck.deckId })
                        });
                        
                        if (response.ok) {
                          const blob = await response.blob();
                          const url = window.URL.createObjectURL(blob);
                          const a = document.createElement('a');
                          a.href = url;
                          a.download = `${generatedDeck.deck.metadata.deckTitle || 'pitch-deck'}.pdf`;
                          a.click();
                          window.URL.revokeObjectURL(url);
                        }
                      } catch (error) {
                        console.error('Export error:', error);
                      }
                    }}
                    className="export-btn export-pdf"
                  >
                    <span className="export-icon">📄</span>
                    Export PDF
                  </button>

                  <button
                    onClick={async () => {
                      try {
                        const response = await fetch('/api/export/generate-pptx', {
                          method: 'POST',
                          headers: { 'Content-Type': 'application/json' },
                          body: JSON.stringify({ deckId: generatedDeck.deckId })
                        });
                        
                        if (response.ok) {
                          const blob = await response.blob();
                          const url = window.URL.createObjectURL(blob);
                          const a = document.createElement('a');
                          a.href = url;
                          a.download = `${generatedDeck.deck.metadata.deckTitle || 'pitch-deck'}.pptx`;
                          a.click();
                          window.URL.revokeObjectURL(url);
                        }
                      } catch (error) {
                        console.error('PowerPoint export error:', error);
                      }
                    }}
                    className="export-btn export-pptx"
                  >
                    <span className="export-icon">📊</span>
                    Export PowerPoint
                  </button>
                </div>

                {/* Advanced Export Options */}
                <div className="advanced-exports">
                  <button 
                    className="advanced-toggle"
                    onClick={(e) => {
                      const content = e.target.nextElementSibling;
                      const isOpen = content.style.display === 'flex';
                      content.style.display = isOpen ? 'none' : 'flex';
                      e.target.textContent = isOpen ? '▶ Advanced Exports' : '▼ Advanced Exports';
                    }}
                  >
                    ▶ Advanced Exports
                  </button>
                  
                  <div className="advanced-content" style={{display: 'none'}}>
                    <button
                      onClick={async () => {
                        try {
                          const response = await fetch('/api/export/generate-html', {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify({ deckId: generatedDeck.deckId })
                          });
                          
                          if (response.ok) {
                            const blob = await response.blob();
                            const url = window.URL.createObjectURL(blob);
                            const a = document.createElement('a');
                            a.href = url;
                            a.download = `${generatedDeck.deck.metadata.deckTitle || 'pitch-deck'}.html`;
                            a.click();
                            window.URL.revokeObjectURL(url);
                          }
                        } catch (error) {
                          console.error('HTML export error:', error);
                        }
                      }}
                      className="export-btn export-html"
                    >
                      <span className="export-icon">🌐</span>
                      Export HTML
                    </button>

                    <button
                      onClick={() => {
                        const dataStr = JSON.stringify(generatedDeck.deck, null, 2);
                        const dataBlob = new Blob([dataStr], { type: 'application/json' });
                        const url = window.URL.createObjectURL(dataBlob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = `${generatedDeck.deck.metadata.deckTitle || 'pitch-deck'}.json`;
                        a.click();
                        window.URL.revokeObjectURL(url);
                      }}
                      className="export-btn export-json"
                    >
                      <span className="export-icon">📁</span>
                      Save JSON
                    </button>
                  </div>
                </div>
              </div>

              {/* PowerPoint Editor Button */}
              <div className="editor-actions">
                <GradientButton
                  onClick={() => setShowSlideEditor(true)}
                  size="large"
                  glow={true}
                >
                  <span>🎨</span>
                  <span>Open PPT Editor</span>
                </GradientButton>
              </div>

              {/* Slides Preview */}
              <div className="slides-section">
                <h3 className="slides-title text-gradient">
                  📋 Your Pitch Deck Slides
                </h3>
                
                <div className="slides-grid">
                  {generatedDeck.deck?.slides?.map((slide, index) => (
                    <div key={index} className="slide-card">
                      <div className="slide-header">
                        <div className="slide-number">
                          {index + 1}
                        </div>
                        <h4 className="slide-title">
                          {slide.title?.replace(/^Slide \d+:\s*/, '') || 'Untitled Slide'}
                        </h4>
                      </div>
                      
                      <div className="slide-content">
                        {Array.isArray(slide.content) ? (
                          <ul className="slide-list">
                            {slide.content.map((item, i) => (
                              <li key={i} className="slide-list-item">
                                {item}
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <p className="slide-text">{slide.content}</p>
                        )}
                      </div>
                      
                      {slide.notes && (
                        <div className="slide-notes">
                          <div className="notes-header">
                            🎤 Speaker Notes
                          </div>
                          <div className="notes-content">
                            {slide.notes}
                          </div>
                        </div>
                      )}
                    </div>
                  )) || (
                    <div className="empty-slides">
                      <div className="empty-icon">📋</div>
                      <p className="empty-text">No slides found</p>
                    </div>
                  )}
                </div>
              </div>
            </GlassCard>
          </div>
            </section>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="app-footer">
        <div className="container">
          <p className="footer-text">© 2025 Pitch Deck Agent</p>
        </div>
      </footer>

      {/* Slide Editor Modal */}
      {showSlideEditor && generatedDeck && (
        <SlideEditor
          deckData={generatedDeck}
          onClose={() => setShowSlideEditor(false)}
          onSave={(updatedDeck) => {
            setGeneratedDeck({
              ...generatedDeck,
              deck: updatedDeck
            });
            setShowSlideEditor(false);
          }}
        />
      )}
    </div>
  );
}

export default App;